spring:
  rabbitmq:
    host: ${AMQP_HOST:localhost}
    port: ${AMQP_PORT:5672}
    username: ${AMQP_USERNAME:guest}
    password: ${AMQP_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh